### ISSUE TITLE
Empty results

### ISSUE THREAD

**Issue by mono424** [daohoangson/flutter-stockfish#1]
I got your package working inside my project. First of all thank you for this!

So my problem is now i always get empty results from stockfish.uci.

`String res = await stockfish.uci("go movetime 3000");` is just returning empty string.

`print(await stockfish.traceEval());` is working, but not updateing.

**Comment by daohoangson** [comment]
Only trace eval works for now, sorry. Support custom UCI command is currently not working. This plugin is being redone, I'll let you know when it's available.

**Comment by mono424** [comment]
alright thank you, really looking forward to it ! :)

**Comment by mono424** [comment]
any updates ? I am working on an free chess app, users really wanna play with stockfish :)

**Comment by Taimor80** [comment]
> any updates ? I am working on an free chess app, users really wanna play with stockfish :)

You may check this 
https://github.com/ArjanAswal/Stockfish

**Comment by ArjanAswal** [comment]
[Pub package](https://pub.dev/packages/stockfish)
[Repository](https://github.com/ArjanAswal/Stockfish)

**Comment by mono424** [comment]
@Taimor80 @ArjanAswal Guys awesome ! Thank you!
